# SPDX-License-Identifier: LicenseRef-CSSL-1.0
# OAI (Duranta) nrUE for the 5G SA attach over the RF simulator. The subscriber is the Open5GS test subscriber
# (IMSI 001010000000001, DNN internet, SST 1); K and OPc are the public test vectors from the Open5GS documentation,
# not secrets. No placeholder. The UE opens a utun for the PDU session, which needs root; see run-5gsa-oai-root.sh.
#   sudo <oai build dir>/nr-uesoftmodem -O <CONFDIR>/oai-5gsa/ue.conf --rfsim '--rfsimulator.[0].serveraddr' 127.0.0.1 \
#     -r 106 --numerology 1 --band 78 -C 3619200000
uicc0 = {
  imsi = "001010000000001";
  key = "465B5CE8B199B49FAA5F0A2EE238A6BC";
  opc = "E8ED289DEBA952E4283B54E88E6183CA";
  dnn = "internet";
  nssai_sst = 1;
  pdu_sessions = ({ dnn = "internet"; nssai_sst = 1; });
}
